---

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TopicName:
    Type: String
    Description: Name of the sns topic
    Default: ashtest-01

Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

Outputs:
  SNSTopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref MyTopic




# Usage:
#   aws cloudformation validate-template --template-body file://./cfn-create_sns_topic.yaml
#   aws cloudformation create-stack --stack-name sns-topic-ashtest-01 --template-body file://./cfn-create_sns_topic.yaml
#   aws cloudformation describe-stacks --stack-name sns-topic-ashtest-01
#   aws cloudformation delete-stack --stack-name sns-topic-ashtest-01
